export const MARK_PRODUCT_AS_FAVORITE= 'app/MARK_STUDENT_AS_FAVORITE'
export const DISSMARK_PRODUCT_AS_FAVORITE= 'app/DISSMARK_PRODUCT_AS_FAVORITE'
export const ADD_TO_FAVORITES_BEGIN='app/ADD_TO_FAVORITES_BEGIN'
export const ADD_TO_FAVORITES_END='app/ADD_TO_FAVORITES_END'